---
root: true

env:
  browser: true
  es2021: true
  node: true

extends:
  - eslint:recommended
  - plugin:prettier/recommended

plugins:
  - prettier

parserOptions:
  ecmaVersion: 2021
  sourceType: module

rules:
  prettier/prettier: error
