---
name: PHP Linting (Overtrue)
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  # This is how to reuse this workflow:
  #  call-workflow:
  #    uses: WorkOfStan/seablast-actions/.github/workflows/overtrue-phplint.yml@main
  phplint:
    runs-on: "${{ inputs.runs-on }}"
    # Limit the running time
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
          # Fetch all history for all branches and tags. Otherwise github.event.pull_request.base.ref SHA isn't found.
          fetch-depth: 0
          # git credentials are needed later, `false` would be safer: token not left in git config
          persist-credentials: true

      # Fetch latest changes (even by previous job)
      - name: Fetch latest changes
        if: ${{ !startsWith(github.ref, 'refs/pull/') }}
        run: git pull --ff-only origin "${GITHUB_REF}"
        env:
          GITHUB_REF: ${{ github.ref }}
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check PHP syntax errors
        uses: overtrue/phplint@9.7.2
