---
name: PHP Linting (Overtrue)
on:
  workflow_call:

permissions:
  contents: read

jobs:
  # This is how to reuse this workflow:
  #  call-workflow:
  #    uses: WorkOfStan/seablast-actions/.github/workflows/overtrue-phplint.yml@main
  phplint:
    runs-on: ubuntu-latest
    # Limit the running time
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check PHP syntax errors
        uses: overtrue/phplint@9.5.3
