---
name: Prettier-fix
on:
  push:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - "notest/**"
  pull_request:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - "notest/**"

# no top level permissions
permissions: {}

jobs:
  prettier-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Limit the running time
    timeout-minutes: 10
    steps:
      - name: Invoke the Prettier fix
        uses: WorkOfStan/prettier-fix@v1
        with:
          commit-changes: true

  commit-check:
    needs: prettier-fix
    runs-on: ubuntu-latest
    # use permissions because pull-request comments are used
    permissions:
      contents: read
      pull-requests: write
    # Limit the running time
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
        with:
          # checkout PR HEAD commit
          ref: ${{ github.event.pull_request.head.sha }}
          # required for merge-base check
          fetch-depth: 0
          persist-credentials: false
      - uses: commit-check/commit-check-action@v2
        env:
          # use GITHUB_TOKEN because use of pr-comments
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: true
          # to accept dependabot/github_actions/*
          # branch: false # todo might not be necessary as "dependabot[bot]" author is ignored
          author-name: true
          author-email: true
          job-summary: true
          pr-comments: ${{ github.event_name == 'pull_request' }}
