---
name: Prettier-fix
on:
  push:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - "notest/**"
  pull_request:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - "notest/**"

# no top level permissions
permissions: {}

jobs:
  prettier-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Limit the running time
    timeout-minutes: 10
    steps:
      - name: Invoke the Prettier fix
        uses: WorkOfStan/prettier-fix@v1.1.6.1
        with:
          commit-changes: true

  commit-check:
    needs: prettier-fix
    runs-on: ubuntu-latest
    permissions: # use permissions because use of pr-comments
      contents: read
      pull-requests: write
    # Limit the running time
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }} # checkout PR HEAD commit
          fetch-depth: 0 # required for merge-base check
          persist-credentials: false
      - uses: commit-check/commit-check-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # use GITHUB_TOKEN because use of pr-comments
        with:
          message: true
          # to accept dependabot/github_actions/*
          branch: false
          author-name: true
          author-email: true
          commit-signoff: false
          merge-base: false
          imperative: false
          job-summary: true
          pr-comments: ${{ github.event_name == 'pull_request' }}
